### ISSUE TITLE
Access Violation fmd 1.1.1.0 Win64

### ISSUE THREAD

**Issue by akir42019** [fmd-project-team/FMD#787] opened 2020-02-12 16:39 UTC
after updating 1.1.0.0 to 1.1.1.0

13:34:35:407 INFO: "Free Manga Downloader" started with [PID:1196] [HANDLE:18446744073709551615]
13:34:35:708 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 1.1.1.0
               Product Version   : Win64
               Host Machine      : Windows 10 64-bit
               FPC Version       : 3.3.1
               LCL Version       : 2.1.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2020/02/12 15:09:15
               Path              : E:\Free Manga Downloader\fmd.exe
               Process ID        : 1196
               MainThread ID     : 10512
13:34:39:032 WARNING: "Free Manga Downloader" doesn't exit normally [PID:1196] [HANDLE:328332]
13:34:39:364 EXCEPTION: EAccessViolation - Access violation
                 $0000000100183546
                 $0000000100161467
                 $000000010015083C
                 $0000000100150815
                 $000000010001C76F
                 $000000010001D2DE
                 $000000010002361F
                 $0000000100071E3F
                 $000000010001E99E
                 $000000010001D251
                 $000000010002361F
                 $000000010002A6D4
                 $0000000100003E0C
                 $0000000100003E86
                 $00000001000186A0
                 $0000000100003457
                 $00007FFB04507BD4
=== Log Session Started at 12-02-2020 13:35:55 by Free Manga Downloader ===

**Comment by JavikusRod** [comment] 2020-02-12 17:01
Same

**Comment by JLChamberlain** [comment] 2020-02-12 17:36
Already been listed [here](https://github.com/fmd-project-team/FMD/issues/785).

**Comment by Tmp341** [comment] 2020-02-12 18:18
Duplicate of #785

**Closed by Tmp341** 2020-02-12 18:18 UTC
Labels: Duplicate
