### ISSUE TITLE
Add support for website  MangaMx

### ISSUE THREAD

**Issue by Unchained0** [fmd-project-team/FMD#603] opened 2019-11-05 23:05 UTC
[https://manga-mx.com/](url)

Spanish Website

**Comment by Slasar41** [comment] 2019-11-06 08:02
Duplicate of https://github.com/fmd-project-team/FMD/issues/171

**Comment by Tmp341** [comment] 2019-11-06 15:35
Main website request title contains a pending note : #351

**Closed by Tmp341** 2019-11-06 15:35 UTC
Labels: Duplicate
