### ISSUE TITLE
I can't download from es.ninemanga.com

### ISSUE THREAD

**Issue by shougoamakusa** [fmd-project-team/FMD#614] opened 2019-11-08 23:29 UTC
NineMangaES, 'es.ninemanga.com', stop working a few days ago, it always downloads the cover of the cap or the same image over and over again

**Comment by acristobo** [comment] 2019-11-09 03:29
I have the same problem

**Comment by Tmp341** [comment] 2019-11-09 09:42
Duplicate of #594

**Closed by Tmp341** 2019-11-09 09:42 UTC
Labels: Duplicate
