### ISSUE TITLE
add web site (EsNiadd)

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#701] opened 2020-01-01 15:03 UTC
add site please [es.niadd](https://es.niadd.com/)

_Happy New Year and successes this year_

**Comment by Tmp341** [comment] 2020-01-01 15:55
Duplicate of #699

**Comment by Tmp341** [comment] 2020-01-01 15:56
You can follow progress in main requests issue #351

**Closed by Tmp341** 2020-01-01 15:55 UTC
Labels: Duplicate, Site Request
