### ISSUE TITLE
Holymanga still doesnt work on fmd even with the changed domain name

### ISSUE THREAD

**Issue by jillybeans** [fmd-project-team/FMD#790] opened 2020-02-14 03:46 UTC
Holymanga still doesnt work on fmd even with the changed domain name

**Comment by jillybeans** [comment] 2020-02-14 03:49
examples are 
http://w11.holymanga.net/her-summon
http://w11.holymanga.net/solo-leveling

**Comment by Tmp341** [comment] 2020-02-14 05:47
Please reopen an issue, if it hasn't been fixed.

Duplicate of #784

**Closed by Tmp341** 2020-02-14 05:47 UTC
Labels: Duplicate, Partially Fixed
