### ISSUE TITLE
"Save WebP as" doesn't work [MangaPark]

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [fmd-project-team/FMD#15] opened 2019-04-02 11:35 UTC
After seeing the changelog, it seems that this has yet to been tackled. The other day I tried downloading from MangaRock with the previous version and, despite having the "save webpp as" set to png, it still downloaded the images in webpp, which is not supported by my reader of choice.

**Comment by SDXC** [comment] 2019-04-02 16:43
@l-l-l-l-l-l Can you please provide a chapter that didn't work for you? Can you also make a full screenshot of the options tab where you have the webp setting?

**Comment by l-l-l-l-l-l** [comment] 2019-04-02 17:45
OK, this is weird. I tried again with the exact same chapter I discovered the issue with and now it works correctly.

The only thing I did since then in that general area was pressing "apply" after checking and then unchecking "save PNG as JPG", so the only reason that comes to my mind would be that somehow the soecification was saved only halfway before (i.e. it knew that the option was selected as PNG but for some reason it acted as if it was WebP) and that meddling fixed it.

Otherwise, it baffles me.

**Comment by SDXC** [comment] 2019-04-02 17:51
Did you per chance make a clean installation with this fork? Normally a control has a default state. It's possible that it showed PNG, but the config value was not set yet. Changing the value and apply saved the setting in the config afterwards.

**Comment by l-l-l-l-l-l** [comment] 2019-04-02 17:55
It seems the issue may have been with the previous version, possibly. But it's weird that it fixed itself without touching it (no WebP issue fixing notice in the changelog).

If it somehow it happens again, I'll notify it.

**Comment by SDXC** [comment] 2019-04-03 20:11
I tested some things and can't reproduce the problem. It's possible that the move to the new version had a hiccup at the first start with that option and was properly written to the config file afterwards.

I'll close this issue for now. If it happens again, just re-open this issue.

**Closed by SDXC** 2019-04-03 20:11 UTC
Labels: Bug, No Fix Needed
