### ISSUE TITLE
downloads and favorites - the title/site/progress etc colums get reset to default length values

### ISSUE THREAD

**Issue by komaedalove** [fmd-project-team/FMD#749] opened 2020-01-27 04:14 UTC
It changed right after I updated to the new version and the columns get resized to default every time I restart fmd, so they don't fit on my screen.

**Comment by Tmp341** [comment] 2020-01-27 08:21
Maybe new column settings aren't properly written into settings files.

**Comment by dazedcat19** [comment] 2020-01-27 20:39
Everything is fine here. columns width and order saved and restored as expected. @Tmp341 you can test by yourself and close the issue.

**Comment by Tmp341** [comment] 2020-01-28 06:40
Yup, everything is fine here too. 

@komaedalove If you have your FMD in ``C:\`` drive, you might be blocked by ``UAC``. I can only suggest you [this](https://github.com/fmd-project-team/FMD/wiki#fresh-install).

**Comment by Tmp341** [comment] 2020-01-28 07:19
Happened to me too:

![ssss](https://user-images.githubusercontent.com/1683388/73243028-9a31d880-41b7-11ea-8555-915a81448d87.jpg)

**Comment by dazedcat19** [comment] 2020-01-29 02:57
I'm really unable to reproduce the issue.
Is it a permanent repeatable issue or only once after update?
I don't see any changes in the code than could reproduce such issue.
You can take a note with screenshot of how width the column by counting the pixel before you close the program, and compare it with the one in the config.ini

**Comment by komaedalove** [comment] 2020-01-29 04:51
its a repeatable issue
the vtDownload parameter changes without me changing it
open fmd, change the width to the desired ones, close, config.ini values:
```
[vtDownload]
SortColumn=6
SortDirection=0
Column0Width=104
Column0Position=0
Column1Width=778
Column1Position=1
Column2Width=477
Column2Position=2
Column3Width=270
Column3Position=3
Column4Width=237
Column4Position=4
Column5Width=696
Column5Position=5
Column6Width=446
Column6Position=6
```

open and close again

```
[vtDownload]
SortColumn=6
SortDirection=0
Column0Width=74
Column0Position=0
Column1Width=71
Column1Position=1
Column2Width=95
Column2Position=2
Column3Width=121
Column3Position=3
Column4Width=96
Column4Position=4
Column5Width=79
Column5Position=5
Column6Width=108
Column6Position=6
```

open and close 3rd time
```
[vtDownload]
SortColumn=6
SortDirection=0
Column0Width=111
Column0Position=0
Column1Width=106
Column1Position=1
Column2Width=142
Column2Position=2
Column3Width=182
Column3Position=3
Column4Width=144
Column4Position=4
Column5Width=118
Column5Position=5
Column6Width=162
Column6Position=6
```

i wanted to try and make base.ini and config.ini read only and when I did that, the value change stopped happening and the width was the same with every restart, but I wish there was a way to fix iti while still keeping config files writeable.

**Comment by komaedalove** [comment] 2020-01-29 05:22
btw i cant even make the config file read only with the width i want, because when i close the program and make it read-only, it's already changed to the stretched width, i know its just a cosmetic issue but its very annoying

**Comment by SDXC** [comment] 2020-01-29 19:04
@dazedcat19 This looks like a DpiAwareness problem. It might be that VTV multiplies the pixel automatically and when closing FMD the multiplied values are saved instead of the raw ones.

@komaedalove Do you have DPI settings higher than 100% on your machine?

**Closed** 2020-01-30 06:13 UTC
Labels: Bug
