### ISSUE TITLE
Myreadingmanga - Error - cannot access

### ISSUE THREAD

**Issue by leoteesh** [fmd-project-team/FMD#944] opened 2020-04-23 16:01 UTC
Hi,

I cannot seem to access nor download from Myreadingmanga
![image](https://user-images.githubusercontent.com/21075197/80120861-819d4880-8583-11ea-8c60-ec062bbaad73.png)

![image](https://user-images.githubusercontent.com/21075197/80121250-f8d2dc80-8583-11ea-963d-b2a6d8541d16.png)

Can you please help?
Many thanks

**Comment by Slasar41** [comment] 2020-04-23 16:53
You need to use cloudflare workaround for now, example: https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-JapScan
Then it'll download normally.
![image](https://user-images.githubusercontent.com/28888646/80126675-9696cd80-85bd-11ea-9cd5-62c03536f793.png)

**Comment by megumixd** [comment] 2020-04-25 01:41
i have the same problem and i did all the step in the tag user-end fix but didnt work

**Comment by ailengt** [comment] 2020-05-02 13:04
same here, the workaround didn't work for me.

**Comment by Reyeselda95** [comment] 2020-05-16 13:28
The workaround worked for me before, but i'm trying it now and it doens't allows me to do download the manga, what could this be caused by? Will be a static fix for this?

**Comment by megumixd** [comment] 2020-05-18 19:15
:c idont know but i hope the team can fix this soon :c please

**Comment by Slasar41** [comment] 2020-05-18 19:29
The workaround still works fine for me:
![image](https://user-images.githubusercontent.com/28888646/82251924-4c182f00-9978-11ea-83f0-9ee15c9317d4.png)
I just copied all the cookies string and useragent to FMD:
![image](https://user-images.githubusercontent.com/28888646/82252036-7964dd00-9978-11ea-9250-b2038861cefc.png)

**Comment by megumixd** [comment] 2020-05-19 01:11
i already fixed thank to you some of the commands are wrong so i fixed with your image thanks :D <3 

> The workaround still works fine for me:
> ![image](https://user-images.githubusercontent.com/28888646/82251924-4c182f00-9978-11ea-83f0-9ee15c9317d4.png)
> I just copied all the cookies string and useragent to FMD:
> ![image](https://user-images.githubusercontent.com/28888646/82252036-7964dd00-9978-11ea-9250-b2038861cefc.png)

**Closed** 2020-05-19 11:10 UTC
Labels: Cloudflare, User-End Fix, Workaround
