### ISSUE TITLE
A cleanup of languages pack po

### ISSUE THREAD

**Issue by jsoudeer** [fmd-project-team/FMD#209] opened 2019-05-27 14:15 UTC
Hello,

When i translate the po from english into french, i noticed some sentences that I did not find in FMD, or duplicate sentences. Do you have the same feeling? In this case would it be possible to specify in the English OP the unused sentences?

Thanks

johan

**Comment by Slasar41** [comment] 2019-05-27 14:44
Yes, some string already not used on FMD because some features got moved to other places and renamed without cleaning up the old string. Maybe the former developers forgot about it.

**Comment by Tmp341** [comment] 2019-05-27 15:55
Former developer added those strings when he thought they are necessary, that made the whole language file problematic.

You need to have some coding knowledge.

**Comment by SDXC** [comment] 2019-05-27 15:59
The Lazarus IDE automatically generates and cleans up the PO files. The problem is that dynamically generated strings are also removed from the PO files which isn't good. That's why it became a manual work and it's easier to let old strings in the PO files than looking through them to find out which we actually don't need anymore. So, if you find any strings that aren't used anywhere, just ignore them.

One of my first mistakes was, that I used the automatically generated PO files which resulted in a loss of many translated strings.

I'll close this issue, as we won't change anything for now.

**Closed by SDXC** 2019-05-27 15:59 UTC
Labels: Question
