### ISSUE TITLE
issue with the sites [ReadManga Today] and [HolyManga]

### ISSUE THREAD

**Issue by jillybeans** [fmd-project-team/FMD#641] opened 2019-11-27 00:38 UTC
Both just stay in a loading loop at the manga info tab with nothing ever finish loading and freezes when i try something else. im able to make it unfreeze by ending the process of the cf_bypass in the task manager but then its says N/A.

this issue is a recent problem and these sites were working yesterday
the site itself still work, just not on fmd.

https://www.readmng.com/god-of-martial-arts
http://ww7.holymanga.net/nanatsu-no-taizai

and its not my version of fmd, since i redownloaded a fresh copy and tried again and it still happends

**Comment by GDXN** [comment] 2019-11-27 03:21
It also happen in Kissmanga, the problem is possibly related to changes in cloudfare.

**Comment by alatnet** [comment] 2019-12-01 01:43
Ah, yea, so this is what was the problem.
To "fix" (i.e. have your favorites list actually finish scanning) you can rename cf_bypass.
You wont be able to get updates from sites that use cloudflare but at least your favorites list will actually finish scanning.

**Comment by SDXC** [comment] 2019-12-01 10:55
you can simply disable cloudflare bypass in the options of fmd. there is no need to rename files.
after disabling cf_bypass you can do the manual workaround for the websites in question.

i'll let you know as soon cf_bypass is fixed.

**Comment by alatnet** [comment] 2019-12-01 15:09
Good to know, didnt know that there was a setting for that.

**Comment by ivanm48** [comment] 2019-12-05 14:49
The same thing happens to me with Readcomiconline
The entire program freezes, I can't pick some other site site or close the program.
I have to close it in task manager.

**Comment by jillybeans** [comment] 2019-12-09 04:32
the new update fixed everything that I had a problem with, thank you

**Comment by Tmp341** [comment] 2019-12-10 19:10
Then closing this for now.

**Closed** 2019-12-10 19:09 UTC
Labels: Cloudflare, Fixed
