### ISSUE TITLE
LHScans change url and name

### ISSUE THREAD

**Issue by Dgraid12** [fmd-project-team/FMD#757] opened 2020-01-31 10:45 UTC
Well, I wanted to say that the site "LHScans" changed domain and updated the name. I wanted to know if they could help with that ... you can see the chapter list ... see information and add to downloads, but no files are downloaded.

I would appreciate the help!

![imagen](https://user-images.githubusercontent.com/53473707/73533215-a9ea3080-43f4-11ea-9960-785db6c317e6.png)

![imagen](https://user-images.githubusercontent.com/53473707/73533231-b2426b80-43f4-11ea-99d9-39ad918d9487.png)

**Comment by Tmp341** [comment] 2020-01-31 13:55
Duplicate of #756

**Closed by Tmp341** 2020-01-31 13:55 UTC
