### ISSUE TITLE
Can we have "Change 'saveto'" apply to multiple rows in the faves list?

### ISSUE THREAD

**Issue by shimizurei** [fmd-project-team/FMD#250] opened 2019-06-12 12:32 UTC
The context menu option "change saveto" can only be used line-by-line. It's very tedious. Since changing the saveto location in the settings doesn't apply to the favorites list, you have to use the right-click menu. It's kind of annoying. Would you please consider fixing this?

**Comment by Slasar41** [comment] 2019-06-12 13:26
Duplicate of https://github.com/fmd-project-team/FMD/issues/10

**Comment by Tmp341** [comment] 2019-06-12 13:40
Duplicate of #10 like @Slasar41 said.

**Closed by Tmp341** 2019-06-12 13:40 UTC
Labels: Duplicate
