### ISSUE TITLE
Not Able to Download [Mangadex]

### ISSUE THREAD

**Issue by VijayThagriya** [fmd-project-team/FMD#112] opened 2019-04-16 10:15 UTC
Tried Few Link of the website , not able to capture manga list .

**Comment by Tmp341** [comment] 2019-04-16 11:05
They have migitation again i think, use CF workaround.

**Comment by BadChase** [comment] 2019-04-16 13:05
I have the same issue from MangaDex, even tried the CF workaround and still cant download nor load manga information. No problem to watch it in my Firefox.

**Comment by Tmp341** [comment] 2019-04-16 13:09
You need to log in to your account, then get necessary cookies.

**Comment by BadChase** [comment] 2019-04-16 13:16
I have done that too. Followed the CF workaround from the old FMD wiki. Doublechecked with your wiki. Everything should be correct yet nothing. Any advise?

**Comment by Tmp341** [comment] 2019-04-16 14:56
![ssssassssasaassaassa](https://user-images.githubusercontent.com/1683388/56220312-e79de880-6070-11e9-8c44-273a2fbd7452.jpg)

**Comment by anfgomezmo** [comment] 2019-04-16 15:38
It is working with the cookies, I can confirm. Probably FMD isn't loading your cookies. Follow these steps: 
1. Log into Mangadex and copy __cfduid, cf_clearance, mangadex_session, mangadex_rememberme_token
2. Go to Mangadex in FMD and add those items line by line and do not forget the ;
3. Add the UserAgent (you can find it where you grab the cookie info)
4. Apply, check if the changes were applied in the cookie and the user agent in FMD (sometimes the cookie won't load) 
Try to see if Mangadex load, I didn't restart FMD.

**Comment by hypomaniak** [comment] 2019-04-16 19:35
Apply, check if the changes were applied in the cookie and the user agent in FMD (sometimes the cookie won't load)

How can you check that?

**Comment by RFIQ** [comment] 2019-04-16 21:08
So, I did all the MD+CF workaround (using info from Firefox once, deleted and then using info from Chrome once) and neither both working at all with FMD.

I did all the cookies and user-agent as told in the comments above but no avail.

Double checked if the cookies lines are there after restarting FMD and it's still there alright.

Any ideas why it still won't load the chapters?

**Comment by Tmp341** [comment] 2019-04-17 04:36
> 
> 
> Apply, check if the changes were applied in the cookie and the user agent in FMD (sometimes the cookie won't load)
> 
> How can you check that?

Just restart FMD after applying.

> 
> 
> So, I did all the MD+CF workaround (using info from Firefox once, deleted and then using info from Chrome once) and neither both working at all with FMD.
> 
> I did all the cookies and user-agent as told in the comments above but no avail.
> 
> Double checked if the cookies lines are there after restarting FMD and it's still there alright.
> 
> Any ideas why it still won't load the chapters?

Have you logged in your account?

**Comment by nille02** [comment] 2019-04-17 07:03
I Face the same. I did all that is in the workaround but it did not work.

**Comment by hypomaniak** [comment] 2019-04-17 08:18
Same situation for me, I never managed to get the CF workaround successful.
I tried getting the settings from Firefox, from Chrome, with and without login, etc...

The FMD log is not helpful in this kind of situation.

**Comment by Tmp341** [comment] 2019-04-17 08:21
FMD only logs chapter and lua related errors, since that N/A isn't chapter related error, it won't log it normally.

**Comment by Tmp341** [comment] 2019-04-17 08:22
> 
> 
> I don't know why its working for you, but its not working for me and its looks like not for @RFIQ
> 
> I even renew the cookies and set it up again, but no luck.
> 
> But since you like images.
> ![derp](https://user-images.githubusercontent.com/4272018/56270910-879e5500-60f7-11e9-8d93-7968245c9f51.png)
> 
> Don't get distracted with the ; at the end
> 
> ![derp2](https://user-images.githubusercontent.com/4272018/56271013-c207f200-60f7-11e9-8d66-c706198f984f.png)

Looks exaclty same. Please try removing ``;`` at the last line, and put ``0`` to ``UpdateListDirectoryPageNumber``.

**Comment by hypomaniak** [comment] 2019-04-17 08:24
I was just trying that.
No ; and 0, no difference.

Also, with or without mangadex_rememberme_token, no difference

**Comment by nille02** [comment] 2019-04-17 08:39
> Looks exactly same. Please try removing `;` at the last line, 

Like i said, don't get distracted by it. It was already gone

> and put `0` to `UpdateListDirectoryPageNumber`.

No Change

**Comment by Tmp341** [comment] 2019-04-17 08:46
I've run out of ideas, @SDXC please help me out.

**Comment by mastafrooper** [comment] 2019-04-17 09:15
It's hit and miss for me. Sometimes I open FMD even with the CloudFlare stuff and it works. SOmetimes not.

I assume there must be some deeper protection that kicks in at times. Or I could just get lucky and Cloudflare is coming and going and the workaround never works.

**Comment by RFIQ** [comment] 2019-04-17 09:30
> Have you logged in your account?
> 
> `__cfduid=`
> `cf_clearance=`
> `mangadex_session=`
> 
> You need these 3 entries (maybe 4 if you checked `remember me` marker). I did those and this was the result :
> ![ssssasa](https://user-images.githubusercontent.com/1683388/56220888-e4572c80-6071-11e9-8ab2-c193078ac2a9.png)
> 
> `MaxTaskLimit:1`
> `MaxThreadPerTaskLimit:1`
> `MaxConnectionLimit:1`
> `UpdateListNumberOfThread:1`
> 
> These are my settings also. If you enter higher numbers or leave default 0 (if your main defaults aren't 1 already), you might get flagged by CF and trigger their anti-bot features.


> 
> 
> I don't know why its working for you, but its not working for me and its looks like not for @RFIQ
> 
> I even renew the cookies and set it up again, but no luck.
> 
> But since you like images.
> ![derp](https://user-images.githubusercontent.com/4272018/56270910-879e5500-60f7-11e9-8d93-7968245c9f51.png)
> 
> Don't get distracted with the ; at the end
> 
> ![derp2](https://user-images.githubusercontent.com/4272018/56271013-c207f200-60f7-11e9-8d66-c706198f984f.png)

@Tmp341 yes I logged into my MD account and that's exactly the lines and settings that I use in my FMD.
So an hour ago I tried again, with Firefox first. No luck with the cookie settings again.

But for Chrome (tested twice), I manage to get the cookies and user-agent works for some reason and one thing that I noticed when testing with both Firefox and Chrome info, FMD seems not updating the manga list when using Firefox info but it does update with Chrome info.

Is it an issue with a specific browser or something when using FMD? Or the site just magically allows me to load the chapters through MD now?

Anyway I can load and download the chapters now, thanks for those who helped.

**Comment by Tmp341** [comment] 2019-04-17 10:11
There some alternative cookies Firefox isn't showing. But i'm using Firefox cookies and it works for me.

**Comment by nille02** [comment] 2019-04-17 13:33
After many trys and redo the steps again and again it worked. I just used Firefox. 

Would be fpCEF3 not a solution for the problem? It can handle the CF Challenge and we don't have to do it manual. 

Until now the ddos protection didn't concern me. I just waited and run a check at a time without a high load. But since days it was active :/

**Comment by Tmp341** [comment] 2019-04-17 13:55
@SDXC is working on a permanent CF utility in Pascal language (FMD's base language). He doesn't know anything about it, thats why we haven't got any progress till now.

**Comment by nille02** [comment] 2019-04-17 14:17
fpCEF3 is a pascall binding for chromium. 

tachiyomi did now something similar with WebView to fix the CF and Login problem (You can Open the Website with Webview, Login and the App can use the Cookies).

**Comment by Tmp341** [comment] 2019-04-17 14:21
I think @SDXC wants to build something inside, ther than a 3rd party app (even if it is open source).

**Comment by nille02** [comment] 2019-04-17 15:01
Its just an Option. It has its advantages because you don't has to bother anymore about bot protections and in case of a captcha you can open a pop up and let the user solve it.

**Comment by SDXC** [comment] 2019-04-17 15:07
@Tmp341 I have made some progress. It's just really disappointing because this Pascal's Regex implementation is absolute shit. >_>

@nille02 fpCEF3 is kind of a last resort. If I'm not able to do it directly, I will evaluate other solutions first.
From what I can see in the readme.md of fpCEF3 is that you have to extend a system environment variable and that's something I absolutely loathe. FMD is portable and something like changing around system settings is not acceptable.

**Comment by ChocolateOtaku** [comment] 2019-04-17 15:39
I think it's just a metter of time until Captchas will arrive because of excessive usage...
Here i found a workaround for HakuNeko:
https://sourceforge.net/p/hakuneko/discussion/general/thread/02be95c5e0/

**Comment by nille02** [comment] 2019-04-17 15:44
The Problem with the environment variable can be solved, i guess. At application start you can extend path by your local path where chrome_elf.dll and icudtl.dat are located. so its not necessary.

**Comment by Tmp341** [comment] 2019-04-17 16:56
> 
> 
> I think it's just a matter of time until Captchas will arrive because of excessive usage...
> Here i found a workaround for HakuNeko:
> https://sourceforge.net/p/hakuneko/discussion/general/thread/02be95c5e0/

I'm always setting minimum limits. And I advise it. Because of excessive usage, Mangadex and many others started using CF protection (yes i'm aware of Mangadex's DDoS attacks, but it started before those).

I don't want to use online readers, some of them has very bad designed interfaces. I'm downloading from mangadex between ``20 kb/s`` - ``200 kb/s`` speeds. I just want to read offline, send some chapters to my phone to read while on the road etc.

But if people only use minimum limits when CF ban appears, it will end up like that.

Some people might know, there is an app called JDownloader. It is designed to be used as a free/premium file share downloader. Around it's early days, there was no captcha or speed limitations. But when people started using this app and others without limitations, online file sharers started taking precautions, like speed limitations and later captcha. If that captchas doesn't use a patterns, normal apps can't fill in those without a human. 

This will end up like that.

**Comment by azraei97** [comment] 2019-04-17 17:25
> 
> 
> ![ssssassssasaassaassa](https://user-images.githubusercontent.com/1683388/56220312-e79de880-6070-11e9-8c44-273a2fbd7452.jpg)
> 
> ![ssssasa](https://user-images.githubusercontent.com/1683388/56220888-e4572c80-6071-11e9-8ab2-c193078ac2a9.png)
> 
> @VijayThagriya @BadChase @anfgomezmo

Some say do:
1. Log into Mangadex and copy __cfduid, cf_clearance, mangadex_session, mangadex_rememberme_token
2. Go to Mangadex in FMD and add those items line by line and do not forget the ;
3. Add the UserAgent (you can find it where you grab the cookie info)
4. Apply, check if the changes were applied in the cookie and the user agent in FMD (sometimes the cookie won't load)

I not even have single clue what he talking about. Login Mangadex done but copy __cfduid, cf_clearance, mangadex_session, mangadex_rememberme_token  ??? What is that? They saying cookie but I still don't understand.

**Comment by azraei97** [comment] 2019-04-17 17:32
The only stable solution for mangadex problem I think FMD should add MangaDex in Options > Websites > Accounts because when I read here they saying about can't work anymore without login to MangaDex first.

**Comment by Tmp341** [comment] 2019-04-17 17:35
> I not even have single clue what he talking about. Login Mangadex done but copy __cfduid, cf_clearance, mangadex_session, mangadex_rememberme_token ??? What is that? They saying cookie but I still don't understand.
Read this : 
https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation

You're basically doing same thing. But you will have different entries. And you can't get Mangadex chapters without logging in (they've activated another protection layer along with Cloud Flare. FMD can't get list without username and password).

**Comment by azraei97** [comment] 2019-04-17 18:07
> 
> 
> > I not even have single clue what he talking about. Login Mangadex done but copy __cfduid, cf_clearance, mangadex_session, mangadex_rememberme_token ??? What is that? They saying cookie but I still don't understand.
> > Read this :
> > https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation
> 
> You're basically doing same thing. But you will have different entries. And you can't get Mangadex chapters without logging in (they've activated another protection layer along with Cloud Flare. FMD can't get list without username and password).

Ok now I understand. Done doing like that and still does not work.

Edit: Now it works. I forget to click Enable after done add Cookies and UserAgent

**Comment by ivanm48** [comment] 2019-04-17 18:21
I tried the steps that work for you, I added the mentioned cookies and user agent, clicked enable and entered the value "1" for the mentioned parameters and it still doesn't work.

Maybe they just have an added protection layer and for some people the CF Workaround works and for some it doesn't.

**Comment by anfgomezmo** [comment] 2019-04-17 18:45
Hello, as I said yesterday. It is working, you need to add the cookies. The session cookie bypasses the username and password layer. However, that cookie expires in one or two days, so you need to renew all them manually. If you are having a problem is with the cookies strings. For example, you need to check after applying and enabling that FMD isn't adding extra numbers at the end of the cookies (FMD adds the last number string into the cookies from the CUID if they can't be recognized) if that happens you need to re-add the cookie because the string is incomplete. That's why it is needed that you add the UserAgent. After adding the strings, apply, enable and then double check that the cookies do not have other chars or numbers. 

I understand, it is tedious but you need to have patience and follow all the steps because this is a temporal solution and it is working.

**Comment by dustylancer** [comment] 2019-04-17 20:44
I think that FMD also needs to increase the delay between checking of favourites as well. The new fork now limits the delay between checking to a maximum of 10 sec. Previously I had it at 15 as you would get banned if the delay was any lesser esp. with people having 300+ items in the list of favourites.

**Comment by spamtaztik** [comment] 2019-04-18 00:23
Um, actually you can select ALL lines from the "cookie:" field from your browser and just dump it into MD's "cookies" field in the FMD options (you don't really have to choose only specific lines). That's what I've been doing all along. It's so much faster than only selecting specific fields, copying them to notepad, adding ";", etc etc. MD doesn't seem to care about extra items in the cookie string.

So just highlight the whole thing, copy, paste it into the "cookies" field in FMD, PRESS ENTER to confirm (I used to always forget this), then click "Apply".

Hope this helps.

![Noname](https://user-images.githubusercontent.com/25314447/56328683-41ee9480-61aa-11e9-9488-b1163dba5b0f.jpg)

**Comment by Twoearle** [comment] 2019-04-18 01:24
![image](https://user-images.githubusercontent.com/12878675/56330615-c9121d00-6156-11e9-81f1-798f287138b1.png)

If you go to your mangadex profile settings, you'll find that the cookies indeed expire after a day (or maybe two) so the workaround is essentially temporary until a permanent fix is made. 
In the case of mangadex one option would be fetching the chapters with another app; wait for a fix or maybe find a way to automatically update the cookies (would also be a workaround).
Worst case scenario, you could transfer your favorites to sites like mangarock or kissmanga.

**Comment by Josexv1** [comment] 2019-04-18 01:35
Actually you just need the CF cookies, no need to login in MD or other sites, you're bypassing CF not the website, CF reloads a few times per month, so probably you will need to edit the cookies again and again. Just did it, right now and works just fine, so bad that with the settings i'm downloading file per file instead of using multiple connections, as MD is getting DDoSed by skids...

**Comment by WildCrow** [comment] 2019-04-18 03:30
For me just the cookie from Chrome works fine, the one from Firefox doesn't.

**Comment by Tmp341** [comment] 2019-04-18 03:38
> 
> 
> Actually you just need the CF cookies, no need to login in MD or other sites, you're bypassing CF not the website, CF reloads a few times per month, so probably you will need to edit the cookies again and again. Just did it, right now and works just fine, so bad that with the settings i'm downloading file per file instead of using multiple connections, as MD is getting DDoSed by skids...

Sometimes, they add another layer of protection, you can't get manga list without using your account.

**Comment by rs3mk** [comment] 2019-04-18 05:34
If you have configured the use of proxy in FMD, you must use that same proxy to obtain the mangadex cookie.

**Comment by VijayThagriya** [comment] 2019-04-18 11:31
> ![ssssassssasaassaassa](https://user-images.githubusercontent.com/1683388/56220312-e79de880-6070-11e9-8c44-273a2fbd7452.jpg)
> 
> ![ssssasa](https://user-images.githubusercontent.com/1683388/56220888-e4572c80-6071-11e9-8ab2-c193078ac2a9.png)
> 
> @VijayThagriya @BadChase @anfgomezmo

MangaDex is working again after updating lua files.

**Comment by wuhugm** [comment] 2019-04-19 05:47
Yesterday cookies worked
Now it doesn't
Already cleared cookies before trying again

**Comment by SDXC** [comment] 2019-04-20 21:13
As it seems fixed for the issuer, I'll close this issue.
CF solution is still in the works.

**Closed by SDXC** 2019-04-20 21:13 UTC
Labels: Cloudflare, User-End Fix, Workaround

**Comment by knight109** [comment] 2019-04-22 04:52
mangadex is not working again, it is fine until yesterday.
already updated lua.

**Comment by nille02** [comment] 2019-04-22 05:17
you had to refresh the cookies

**Comment by nille02** [comment] 2019-04-24 07:07
They must have change something again, with the workaround i cant update the favs. can someone else confirm?

**Comment by Tmp341** [comment] 2019-04-24 09:16
Just checked. I haven't changed my cookies since last week. Working on my end (downloading some of my mangas).

**Comment by nille02** [comment] 2019-04-24 09:19
Now its working again, without any change ...

**Comment by Josexv1** [comment] 2019-04-24 12:24
The only solution is to change a the cookies daily in the mangadex module, until a fix is built in. 
I believe this issue can be closed

**Comment by nille02** [comment] 2019-04-24 13:51
it is closed, but even with new cookies it happens that it did not working.

**Comment by knight109** [comment] 2019-04-25 17:38
i dont know if it just me but change the cookies doesnt work anymore.
it worked yesterday tho.

**Comment by nille02** [comment] 2019-04-25 17:39
They have some other protection enabled in there high load times.

**Comment by knight109** [comment] 2019-04-26 05:14
ohh you right, i can do it now

**Comment by nille02** [comment] 2019-04-26 05:16
Because you write now hours later

Tmp341 <notifications@github.com> schrieb am Mi., 17. Apr. 2019, 09:37:

**Comment by nille02** [comment] 2019-04-30 07:18
As a small addition to the Cookie Workaround. I ask myself why it fails sometimes. One reason is the IP Protocol.  In times where is was not working my browser connected thru IPv6 and these cloudflare cookies failed in fmd. Disable IPv6 in my Browser and connect over IPv4 helped. 

To disable ipv6 in Firefox go to the address bar and enter about:config in the search enter network.dns.disableIPv6 and switch it to false. 
Visit Mangadex and get the new cookies.

**Comment by SDXC** [comment] 2019-04-30 09:15
@nille02 Thanks for that info. I always forget about the problems IPv6 brings. I have it disabled (on OS layer) myself, so I also never had problems with the workaround.

**Comment by nille02** [comment] 2019-04-30 09:27
My Final solution was disable ipv6 just for mangadex and readcomicsonline in my dns server (pi-hole)

I guess its posibile to do the same with the windows hosts file if you just add 
`:: mangadex.org`
That should disable ipv6 for this domain.

**Comment by SDXC** [comment] 2019-04-30 09:29
Well in my case I don't need IPv6 anywhere, so I disabled it as long as this keeps being the case.

**Comment by hypomaniak** [comment] 2019-04-30 09:45
Just tried this solution, and it seems to work!
But at the same time, my RSS reader has managed to connect to Mangadex, so maybe it's just the Cloudflare that is off at the moment?

In any case, thanks for the information!!

**Comment by SDXC** [comment] 2019-04-30 09:50
@hypomaniak CF is off. DDoS starts probably around 16:30 (GMT+1h) again. It's been like this nearly everyday lately.

**Comment by hypomaniak** [comment] 2019-04-30 16:28
Yeah, just saw the CF enabled now, and the cookie workaround is not working, even with IPV6 disabled.

**Comment by nille02** [comment] 2019-04-30 16:48
Did the workaround works for you previously? right now its working for me.

**Comment by hypomaniak** [comment] 2019-04-30 16:52
Well, I got the application working for a few days in a row last week, then it got messy again.

I had some time to set up the Lazarus environment this weekend, I will try to look if I can find what is the server answer. Until now, I only found where the cookies are input in the http request.

**Comment by hypomaniak** [comment] 2019-05-01 19:14
After tinkering with the debugger, I think I managed to pinpoint the problem.

Looking for how the cookies are handled between the settings and the modules, I foundthis:
WebsiteModules.pas 
procedure TModuleContainer.PrepareHTTP

The cookies are passed like this:
with Settings.HTTP do
  begin
...
      AHTTP.Cookies.Text:=Cookies;  

Looking at AHTTP.Cookies.Count, it always stayed at 1, as if the string sent from Settings.HTTP is not parsed correctly.

Then, I looked in the MangaDex.lua file and found this:
http.cookies.values['mangadex_h_toggle'] = '1'


so I added these lines in the lua file:
  http.cookies.values['__cfduid'] = ''
  http.cookies.values['cf_clearance'] = ''
  http.cookies.values['mangadex_session'] = ''
  http.cookies.values['mangadex_rememberme_token'] = ''

with the values coming from Firefox, and now it works.

So for me, the problem some people (like me) had with the CF workaround not working is that the method to input the cookies values can lead to different results.
I don't know if this is due to the System Localization (I use a French Win7 with a Belgian keyboard) or whatever, but I would suggest to those who are struggling with this problem to try and modify their LUA file to see if this works.


PS:
I noticed one thing doing this test.
If I wollow [this page](https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation) instructions, I get a some wrong values from Firefox
In the Networking cookies tab, with the "long" cookies, some characters are replaced with ...
So instead of using the cookies tab, I have to go the header tab or the website properties window.

**Comment by Tmp341** [comment] 2019-05-02 04:56
> In the Networking cookies tab, with the "long" cookies, some characters are replaced with ...
> So instead of using the cookies tab, I have to go the header tab or the website properties window.

If you double click on values where you see ``...``, it will show all. Firefox just trying to look short (to fit).

**Comment by hypomaniak** [comment] 2019-05-02 09:05
> Tested, couldn't get chapter list. Reverted to workaround.

Did you leave the module settings enabled?
If not, the useragent is not sent

**Comment by Tmp341** [comment] 2019-05-02 09:32
Yeah, both disabled an enabled.

**Comment by hypomaniak** [comment] 2019-05-04 10:34
Ok, so I found the right solution (for my situation)

Since editing the .lua file requires to restart FMD to reload it, I looked a little more in how the cookie settings are passed to the "low-level" code, and in my case, I have to input every cookie on its own line and WITHOUT any punctuation, so no ;

**Comment by anfgomezmo** [comment] 2019-05-04 15:01
The problem is that you need to change enable to (false), apply, load the cookie no matter if it has all the information, then enable (true) and apply. 

FMD, leave the cookie load if you do not disable, the old cookie will remain in the memory stack so MangaDex is not going to work unless you disable it first then load it.

**Comment by hypomaniak** [comment] 2019-05-04 15:27
> The problem is that you need to change enable to (false), apply, load the cookie no matter if it has all the information, then enable (true) and apply.
> 
> FMD, leave the cookie load if you do not disable, the old cookie will remain in the memory stack so MangaDex is not going to work unless you disable it first then load it.
> 
> Also, it was informed that MangaDex is under a heavy DDoS attack right now so the service will fail in some cases.

Nope, I checked with the debugger: without touching the Enable setting (if it's already checked), what you enter in the Cookies box is saved and used, BUT you need to click on another field to validate what you entered in the Cookies field.

**Comment by anfgomezmo** [comment] 2019-05-05 17:56
> 
> 
> > The problem is that you need to change enable to (false), apply, load the cookie no matter if it has all the information, then enable (true) and apply.
> > FMD, leave the cookie load if you do not disable, the old cookie will remain in the memory stack so MangaDex is not going to work unless you disable it first then load it.
> > Also, it was informed that MangaDex is under a heavy DDoS attack right now so the service will fail in some cases.
> 
> Nope, I checked with the debugger: without touching the Enable setting (if it's already checked), what you enter in the Cookies box is saved and used, BUT you need to click on another field to validate what you entered in the Cookies field.

Weird, I checked too and for me, it was stacking maybe varies from system and configurations. I will test

**Comment by hypomaniak** [comment] 2019-05-05 18:04
Could also be that I don't have the exact same version of all the libs/addons compared to the release version (I checked all the list, so should be ok), but for now I have the same behavior between what I compile and the release.
