### ISSUE TITLE
cf_bypass Virus Alert

### ISSUE THREAD

**Issue by alatnet** [fmd-project-team/FMD#522] opened 2019-09-28 16:27 UTC
Windows Defender keeps popping up with a virus alert about cf_bypass.exe.
Says it has Trojan:Win32/Zpevdo.B and Trojan:Win32/Ludicrouz.V.

**Comment by Tmp341** [comment] 2019-09-28 16:30
Duplicate of #514. Read that issue for more info.

**Comment by Tmp341** [comment] 2019-09-28 16:31
Duplicate of #514.

**Comment by alatnet** [comment] 2019-09-28 16:31
Ah, ok. didnt see that thread.

**Closed by Tmp341** 2019-09-28 16:30 UTC
Labels: Antivirus, Duplicate

**Comment by Tmp341** [comment] 2019-09-28 16:32
> 
> 
> Ah, ok. didnt see that thread.

No problem. Having one issue is both useful for us and users.
