### ISSUE TITLE
mangarock cant download

### ISSUE THREAD

**Issue by ragna0011** [fmd-project-team/FMD#716] opened 2020-01-07 00:39 UTC
last few days, my list cant has check error in mangarock site, but now, it can check but cant seem to download the chapter, is it just me?

**Comment by Tmp341** [comment] 2020-01-07 06:15
Mangarock removes mangas one by one. Our server database has 20k+ mangas listed, but two days ago i checked and FMD only found 9k+ manga. I'm going to update server database, but you can crosscheck a manga on browser.

**Comment by ragna0011** [comment] 2020-01-12 00:04
i read manga rock FAQs i think they started redirection to other websites.

**Comment by lordzidiousback** [comment] 2020-01-12 01:45
the problem is there is no download but check and see chapter they work. download is the only option not work

**Comment by Tmp341** [comment] 2020-01-12 06:05
I've tried downloading yesterday, it seems you can read on the app, but can't read on browser or download via FMD. Maybe, other apps have a solution, i dunno.

**Comment by knight109** [comment] 2020-01-12 12:12
so it broken now or it will fixed later?

**Comment by Tmp341** [comment] 2020-01-13 06:35
> 
> 
> so it broken now or it will fixed later?

Mangarock is closing it's doors, one by one. I suggest you to find an alternative. I couldn't read manga on browser, maybe an account required. But, since mangarock is closing, no it can't be fixed.

**Comment by Tmp341** [comment] 2020-01-14 12:27
I'm closing this issue for now.

**Closed by Tmp341** 2020-01-14 12:27 UTC
Labels: Answered, Limited Access, Question

**Comment by knight109** [comment] 2020-01-17 13:26
> > so it broken now or it will fixed later?
> 
> Mangarock is closing it's doors, one by one. I suggest you to find an alternative. I couldn't read manga on browser, maybe an account required. But, since mangarock is closing, no it can't be fixed.

What are the good alternative website for now?

**Comment by Tmp341** [comment] 2020-01-17 13:35
> 
> 
> > > so it broken now or it will fixed later?
> > 
> > 
> > Mangarock is closing it's doors, one by one. I suggest you to find an alternative. I couldn't read manga on browser, maybe an account required. But, since mangarock is closing, no it can't be fixed.
> 
> What are the good alternative website for now?

I use mangadex + kissmanga.
