### ISSUE TITLE
Access Violation when pressing CTRL after deleting an entry in downloads.

### ISSUE THREAD

**Issue by alatnet** [fmd-project-team/FMD#895] opened 2020-04-08 11:02 UTC
Im getting this:
> 06:59:11:120 EXCEPTION: EAccessViolation - Access violation
>                  $000000010007C380
>                  $000000010015D1F1
>                  $000000010015D231
>                  $000000010015D484
>                  $000000010015FC9A
>                  $0000000100010995
>                  $0000000100167269
>                  $000000010015CB05
>                  $00000001002A3151
>                  $0000000100203D60
>                  $000000010014245F
>                  $0000000100142AAC
>                  $00007FFA80835C0D
>                  $00007FFA80835602
>                  $0000000100143ABD
>                  $0000000100028EC0
>                  $000000010002931F

Whenever i delete an entry in downloads then press CTRL afterwards.
If you dont change pages, and keep pressing CTRL, the access violation will pop up every time you press CTRL.

**Comment by Tmp341** [comment] 2020-04-08 18:02
Duplicate of #829

**Closed by Tmp341** 2020-04-08 18:02 UTC
