### ISSUE TITLE
can not be downloaded [LHScans]

### ISSUE THREAD

**Issue by Dgraid12** [fmd-project-team/FMD#1031] opened 2020-06-14 05:53 UTC
cannot download from lhscans, most likely due to cloudflare

![image](https://user-images.githubusercontent.com/53473707/84585819-922eaa00-ade1-11ea-9527-1cb5525e48fe.png)

![image](https://user-images.githubusercontent.com/53473707/84585841-b25e6900-ade1-11ea-894a-0fa908e488d3.png)

**Comment by Tmp341** [comment] 2020-06-14 10:11
Cloudflare workaround doesn't work?

**Comment by Dgraid12** [comment] 2020-06-14 17:33
> Cloudflare workaround doesn't work?

you mean use cookies? I honestly haven't tried!

**Comment by pclkpg581** [comment] 2020-06-15 05:30
I can confirm the cookie workaround doesn't work for me. I think I've noticed new behavior in the website, though. After the cloudflare check, the URL gets appended with an extremely long key: 
https://loveheaven.net/?__cf_chl_jschl_tk__=******

**Comment by Dgraid12** [comment] 2020-06-15 17:38
it has worked for me taking cookies from here

![image](https://user-images.githubusercontent.com/53473707/84688367-3b25f380-af0d-11ea-8f9c-740695ee9c9f.png)

I copy everything that appears to me in that line and paste it here

![image](https://user-images.githubusercontent.com/53473707/84688491-6d375580-af0d-11ea-9933-3d138a30f56d.png)

**Comment by pclkpg581** [comment] 2020-06-15 22:00
Dgraid12, that's what I did for my cookies, only I use Chrome. It doesn't work, strangely. I'm using release 1.3.3.0 and the latest lua for Lhscans. I use the three cookies: cf_clearance, __cfduid, and PHPSESSID.

**Comment by pclkpg581** [comment] 2020-06-16 03:23
I managed to get it working. I kept entering invalid cookies, because the repeated cloudflare checks kept changing the cookies. My mistake. Hopefully the cookies endure this time.

**Comment by pclkpg581** [comment] 2020-06-16 03:51
Scratch that, the cloudflare instance seemed to reset again, and the new cookies don't seem to fix it again. I'll continue looking for a workaround.

**Comment by TienVer** [comment] 2020-06-16 06:57
Tried updating my cookie parameters (never needed cf_clearance to get the download working, but I appended it to the string anyway), to no avail. Chapter count is still 0 and FMD can't even access the series info page.

**Comment by dazedcat19** [comment] 2020-06-16 22:05
cloudflare's session only last a day. some even only for 12 hours. so you have to get a new session when it's expired.
you can try fmd2. it can bypass the basic cloudflare challenge. https://github.com/dazedcat19/FMD2

**Comment by Dgraid12** [comment] 2020-06-17 01:33
good .. I also had several problems today when trying to use the program with cookies manually .. I generally used the ones given by firefox and today I tried with chrome cookies and it worked!

![image](https://user-images.githubusercontent.com/53473707/84844663-d5269280-b018-11ea-80af-36b8e6c778cd.png)

![image](https://user-images.githubusercontent.com/53473707/84844710-f6877e80-b018-11ea-99c6-ec4d2f2d8145.png)

**Comment by pclkpg581** [comment] 2020-06-17 01:44
I think it's likely the cloudflare bypass needs an update, to avoid these unreliable workarounds. I haven't gotten it working once since the last time. Hopefully the bypass updates (https://github.com/fmd-project-team/FMD/pull/1003) submitted by smol-kaguya fixes this as well. I couldn't get FMD to compile for testing it.

**Comment by TienVer** [comment] 2020-06-17 10:05
Tried FMD2 at your suggestion and migrated my settings (am currently in the middle of curating my old favorites list), but while the software can now access the series' profile page, properly displays the correct number of chapters in the favorites pane and even start a download task, it only collects the Loveheaven recruitment page and nothing else. It's still stuck at, e.g. 0/24, @0Bps.

Then I saw in developer tools that __cfduid had changed, but even updating that in the cookie string didn't do the trick. Aside from PHPSESSID, cf_clearance and __cfduid, is there any other parameter I must add to FMD2's cookie settings?

**Comment by Inareous** [comment] 2020-06-17 15:37
More often than not, there will be a chance for human error in pasting cookies.

To bypass cf (in general), after you get your session on your browser, all you need to copy is cf_clearance and __cfduid for cookies, and your browser's User-Agent (the cookies is tied to the User-Agent).

**Comment by TienVer** [comment] 2020-06-17 16:21
Well, I'm not seeing the aforementioned __cf_chl_jschl_tk__=****** addition to the site URL anymore, so it's possible the site owner rolled out a new tweak then decided to roll it back.

**Comment by pclkpg581** [comment] 2020-06-17 21:38
I can confirm the same as TienVer. Old behavior seems to have been restored for now.

Some more details on the differences:
Updating to the new cookies didn't respond with the website's aggressive cloudflare that implemented the cf_chl_jschl_tk=****** change. Each time I tried the new cookies, FMD still couldn't access the site. With the cf_chl_jschl_tk=****** version, cf_clearance was added to the cookies; now with the rollback, it's back to requiring only __cfduid and PHPSESSID.

After looking into it a bit more, the cf_chl_jschl_tk string seems to be appended to the url when the website is "Under Attack". It looks like they might have been DDOS'd.

**Comment by TienVer** [comment] 2020-06-19 07:13
New hiccups today. Downloads worked yesterday, though.

Tried updating the __cfduid parameter, but FMD only downloads the recruitment pages.

**Comment by pclkpg581** [comment] 2020-06-19 07:50
TienVer: I've experienced the same thing. The cause may be similar to another recent issue (https://github.com/fmd-project-team/FMD/issues/1035). I'm getting cloudflare error 1020 when attempting to access mangalib.me and the image sources on LHScans. Again, it looks like cloudflare settings set by the site admins are blocking access somehow.

**Comment by TienVer** [comment] 2020-06-19 15:00
FMD2 seems willing to download, though for some strange reason it waited for something like half a minute before it started collecting the pages. I updated __cfduid beforehand, but the download was not immediate. Weird, but I won't look the gift horse in the mouth.
FMD, on the other hand, is still banging its head on the wall.

**Comment by Dgraid12** [comment] 2020-06-19 18:11
in FMD2 it is working normally, without putting cookies or anything else, it seems that they deactivated the cloudflare

**Comment by Slasar41** [comment] 2020-06-19 20:06
Should be fixed.

**Closed by Slasar41** 2020-06-19 20:06 UTC
Labels: Cloudflare, User-End Fix, Workaround
