### ISSUE TITLE
Issues with downloading [MangaDex, LHTranslation, KissManga]

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [fmd-project-team/FMD#2] opened 2019-03-30 18:39 UTC
I have yet to update to this repository, but since what I have issues with seems unchanged, I'll mention it here:

-Someone fixed the lua for LHTranslations and posted it at Riderkick's issues. You should update the old lua.
-I seem to have some issue with Mangadex despite the cookies workaround; someone should check that and give a solution.

I'd mention the ongoing Kissmanga issue, but it seems that it's one of your priorities.

**Comment by SDXC** [comment] 2019-03-30 21:46
The fixed LHTranslation script is now merged, but for it to work you have to use a Cloudflare workaround:
https://github.com/SDXC/FMD/wiki/CF-Workaround:-LHTranslation

**Comment by SDXC** [comment] 2019-03-31 03:52
Here's the first release of this fork:
https://github.com/SDXC/FMD/releases/tag/0.9.160.0

Regarding MangaDex: At the moment, there doesn't seem to be anymore DDoS attacks, so Cloudflare isn't blocking right now. Please retry and let me know if it works.

**Comment by anfgomezmo** [comment] 2019-03-31 03:59
MagaDex is working fine after the DDoS attack. I will check the other sites in some hours. I think KissManga must be a priority since it is very popular, what do you think??

**Comment by SDXC** [comment] 2019-03-31 04:05
I will look into the problems with KissManga, but it will probably take some time because KissManga itself seems to be a real pain.

**Comment by Tmp341** [comment] 2019-03-31 06:35
SDXC, can you give me a position, so i can assign you, close unnecessary issues etc?

**Comment by SDXC** [comment] 2019-03-31 11:51
@Tmp341 You're added now. Please go to the teams page (Support) and write on the discussion board. Further talk will be held there.

**Comment by Owyn** [comment] 2019-03-31 15:33
KissManga doesn't work on this FMD too, only on website 
![изображение](https://user-images.githubusercontent.com/1309656/55291092-7c52e600-53e3-11e9-9aec-c640c61b805f.png)

**Comment by SDXC** [comment] 2019-03-31 15:35
Yes, that's one thing I will look into the next few days.

**Comment by anfgomezmo** [comment] 2019-03-31 18:32
> 
> 
> KissManga doesn't work on this FMD too, only on website
> ![изображение](https://user-images.githubusercontent.com/1309656/55291092-7c52e600-53e3-11e9-9aec-c640c61b805f.png)

Yes, it was already reported and SDXC is checking. I am reading the code so my solution could take a bit more time

**Comment by Vantageright** [comment] 2019-03-31 18:42
For me MangaDex isn't working at all, browser can connect fine but the downloader is just coming up red for every fave I have on the site.

**Comment by SDXC** [comment] 2019-03-31 19:24
@Vantageright MangaDex is currently in mitigation mode, meaning that Cloudflare is running its business once again. I just tested the workaround and it works with it. For now the workaround for MangaDex can be found here: https://github.com/riderkick/FMD/wiki/FAQ

We will put up a more detailed wiki page for that later.

**Comment by Vantageright** [comment] 2019-03-31 19:39
The page lists 5 cookies under the tab yet I only see 4, the missing one is mangadex=

**Comment by SDXC** [comment] 2019-03-31 19:48
That may have changed.
You either need the "mangadex" cookie setting or "mangadex_session".
Both are only available, when you are a logged in user.

I just did it with my own account in a fresh browser session. Without login I got the __cfduid and cf_clearance. After logging in I additionally got the mangadex_session. After putting everything in FMD and updating my UserAgent it worked.

Important: UserAgent has to match completely with the browser where the cookies were taken from.

**Comment by hypomaniak** [comment] 2019-03-31 21:04
Somehow, I can't get the new version to work on LHTranslations, where the old version is still working fine.

Also, both versions can't connect to Mangadex at the moment, but that's probably me getting the settings wrong: I can't get that "mangadex" cookie from either firefox or chrome, but even with the "mangadex_session" cookie it does not work.

Just a clarification: for all those cookie settings, do we need to enter them on different lines on the popup window appearing in the settings, or on a single line?
And for the user agent?

**Comment by admiralmikan** [comment] 2019-04-01 01:43
> Somehow, I can't get the new version to work on LHTranslations, where the old version is still working fine.
> 
> Also, both versions can't connect to Mangadex at the moment, but that's probably me getting the settings wrong: I can't get that "mangadex" cookie from either firefox or chrome, but even with the "mangadex_session" cookie it does not work.
> 
> Just a clarification: for all those cookie settings, do we need to enter them on different lines on the popup window appearing in the settings, or on a single line?
> And for the user agent?

Put the cookies on single line and separate each cookie with ;

_cfduid=XXXXXXXX; cf_clearance=XXXXXXX; mangadex_rememberme_token=XXXXXXX; mangadex_session=XXXXXXX

there's no mangadex=xxxx anymore, you only need mangadex_rememberme_token=xxxx

Also you have to put the right User Agent. Detect your user agent by enter this in your browser https://www.whatismybrowser.com/detect/what-is-my-user-agent

**Comment by hypomaniak** [comment] 2019-04-01 03:57
Yeah, I tried inputting like that, but no connection possible.
I already took the user agent from the browser I was getting the cookies for every try.

**Comment by krakerz** [comment] 2019-04-01 16:39
yeah, i can confirm it's not work even with all the cookies setup

**Comment by SDXC** [comment] 2019-04-01 16:49
@krakerz I checked it right now without any cookies set (advanced settings disabled) and it works for me right now. Also it is still 1. April, so try to endure it a little bit. We are not sure, if some of these problems happen because of some pranks or not.

**Comment by hypomaniak** [comment] 2019-04-01 16:50
Well, the old version still works fine with Mangadex at the moment, it's just when their website is in CF mode that it's a pain.

**Comment by krakerz** [comment] 2019-04-01 16:51
@SDXC yeah, i'm pretty much it's due april fool, since 31th still fine LMAO

**Comment by Tmp341** [comment] 2019-04-01 16:58
Lhtranslation was woring for me yesterday, with the cookies workaround.

**Comment by SDXC** [comment] 2019-04-01 21:46
Some smaller networking problems could possibly come from the old version of a component (Synapse) that was too old. I updated that component for the next release. I'm waiting for some feedback and will release the new version afterwards.

**Comment by Twoearle** [comment] 2019-04-02 04:09
I can confirm that adding the User Agent and Cookies headers for mangadex works. 

On the other hand KissManga is under maintenance right now, so i haven't been able to test it.

**Comment by Tmp341** [comment] 2019-04-02 04:42
@Twoearle If you delete kissmanga cookies from browser, that maintenance screen will be gone.

**Comment by Sakurahime08** [comment] 2019-04-02 05:05
is https://myreadingmanga.info/ working? Can't seem to make it connect via FMD. It connects fine in a browser. Thanks!

**Comment by Sakurahime08** [comment] 2019-04-02 05:45
is https://myreadingmanga.info/ working? Can't seem to make it connect via FMD. It connects fine in a browser and in the old FMD. Thanks!

**Comment by Sakurahime08** [comment] 2019-04-02 10:04
Can't also download from Mangahasu. I can access the manga page in FMD but can't download. I've also applied the cookies workaround on it. What to do? Thanks!

**Comment by SDXC** [comment] 2019-04-02 16:08
@Sakurahime08 It works with the new patch (will be online any minute). Please try it, as soon you get the new version of FMD.

**Comment by SDXC** [comment] 2019-04-02 18:00
@Sakurahime08 Official release is out now. The updater in the version 0.9.160.0 doesn't work. You have to update manually. Updater should work for the future releases though.

**Comment by hypomaniak** [comment] 2019-04-02 18:16
0.9.161 works fine for me on LHT and Mangadex, and the new script for LHT has fixed the chapter naming problem (when coming from favorites), thanks !

**Comment by SDXC** [comment] 2019-04-02 18:30
@l-l-l-l-l-l Except for KissManga, does the rest work for you, using 0.9.161.0? This issue is getting overloaded with many different topics, so I want to come to a closure. We will open an ongoing issue for KissManga after closing this one.

**Comment by ayanamichie** [comment] 2019-04-04 03:40
Kissmanga is working too
![image](https://user-images.githubusercontent.com/48865118/55528151-44ad9d80-5672-11e9-88fe-f0472fdf4a52.png)

![image](https://user-images.githubusercontent.com/48865118/55528062-ebde0500-5671-11e9-9837-2c4c6066d126.png)
![image](https://user-images.githubusercontent.com/48865118/55528120-25af0b80-5672-11e9-85ad-d903a1afaf51.png)

![image](https://user-images.githubusercontent.com/48865118/55528086-01532f00-5672-11e9-92d3-7aeabb849ebb.png)
from the 
![image](https://user-images.githubusercontent.com/48865118/55528100-1465ff00-5672-11e9-92a1-211a2bc9a6a6.png)

**Comment by molitar** [comment] 2019-04-05 04:31
> 
> 
> Kissmanga is working too
> ![image](https://user-images.githubusercontent.com/48865118/55528151-44ad9d80-5672-11e9-88fe-f0472fdf4a52.png)
> 
> ![image](https://user-images.githubusercontent.com/48865118/55528062-ebde0500-5671-11e9-9837-2c4c6066d126.png)
> ![image](https://user-images.githubusercontent.com/48865118/55528120-25af0b80-5672-11e9-85ad-d903a1afaf51.png)
> 
> ![image](https://user-images.githubusercontent.com/48865118/55528086-01532f00-5672-11e9-92d3-7aeabb849ebb.png)
> from the
> ![image](https://user-images.githubusercontent.com/48865118/55528100-1465ff00-5672-11e9-92a1-211a2bc9a6a6.png)
> I always get the cookies from one of the adprotect, because have both, and check if the user-agent did not change, cause browsers do update, it was not working initialy till i noticed i copy/pasted missing a single letter, the M for Mozilla, that was silly of me XD

Can you provide instructions on how you get them keys and initialization vector in Firefox?

**Comment by Tmp341** [comment] 2019-04-05 06:23
> 
> 
> Can you provide instructions on how you get them keys and initialization vector in Firefox?


- Open kissmanga.com -> Open a manga chapter's first page.
- Right click -> inspect element -> choose "console"
- Type "chko" and hit enter. Copy and paste what has returned from that code to a blank text file. For example "mshsdf832nsdbash20asdm".
- Now type "CryptoJS.enc.Hex.stringify(iv)" and hit enter. Copy and paste what has returned from that code to a blank text file. For example "a5e8e2e9c2721be0a84ad660c472c1f3"
- Open FMD -> Go to "Settings -> Websites -> Options" tab. Paste those codes to "Key" and Initialization Vector".
- Save.
- Restart FMD.
- Check again.

**Comment by SDXC** [comment] 2019-04-05 11:22
TODO (for me):
* Create a wiki page with a clear and easy to understand step-by-step guide.
* Add a link in FMD to the wiki page, so users can't get to the info easier.

**Comment by Tmp341** [comment] 2019-04-05 14:56
@SDXC Is that ``chko`` method still needed?

**Comment by molitar** [comment] 2019-04-06 05:40
chko does not work with Firefox that is why I asked for Firefox instructions. It's a pain to have to open up Google Chrome and log into site everytime.

**Comment by Tmp341** [comment] 2019-04-06 07:08
> 
> 
> chko does not work with Firefox that is why I asked for Firefox instructions. It's a pain to have to open up Google Chrome and log into site everytime.

I can get those codes from Firefox. What i meant is, is it still needed to get?

**Comment by azirio** [comment] 2019-04-06 14:45
Your "chko" values and the "key" value on your example didn't match or how did you find the miss digits?

**Comment by Tmp341** [comment] 2019-04-06 18:13
> 
> 
> Your "chko" values and the "key" value on your example didn't match or how did you find the miss digits?

I've just tried what i've said, and they are working (console codes).

**Comment by krakerz** [comment] 2019-04-06 19:08
for kissmanga i noticed that you only need (i'm too lazy to test to remove 1 or more of those cookies below)
__cfduid
__PPU_SESSION_1_1616193_false
cf_clearance
BB_plg
bbl

cookies, i tested it first in Opera, yet i can't manage to get the BB series cookies and PPU session, but when i switched to chrome, i got all of it and after adding them to the cookies section, it's works fine again :)

**Comment by SDXC** [comment] 2019-04-06 19:32
This issue is getting out of hand. Too much different talks, too much people and no feedback from the actual issuer. Overall the websites mentioned in this ticket work (even though with a bit of tweaking).

That's why I close this issue now. If you keep having trouble with KissManga, either open a new issue ONLY for KissManga or join the Discord server and ask in the support channel.

**Closed by SDXC** 2019-04-06 19:32 UTC
Labels: Bug, Cloudflare, Feedback Pending, Partially Fixed

**Comment by Sakurahime08** [comment] 2019-04-09 02:16
Thank you! @SDXC
