### ISSUE TITLE
Kissmanga Download Issue and Cloudfare Workaround

### ISSUE THREAD

**Issue by Souravi785** [fmd-project-team/FMD#946] opened 2020-04-24 19:29 UTC
I am having problem downloading from kissmanga suddenly. First, when i click a manga for info it shows "Cannot get manga info. Check your internet and try again." After I tried the CF workaround (copied the cookies and user agent in FMD) the manga info shows but anything fails to download. What to do now?

**Comment by Thrieze** [comment] 2020-04-24 21:46
Check this thread.

https://github.com/fmd-project-team/FMD/issues/934

**Comment by Tmp341** [comment] 2020-04-25 07:39
Duplicate of #934

**Closed by Tmp341** 2020-04-25 07:39 UTC
