### ISSUE TITLE
Zero Chapters for comic under the 'Mature' category. [Manhuagui]

### ISSUE THREAD

**Issue by mirlov** [fmd-project-team/FMD#794] opened 2020-02-16 03:59 UTC
I've tried to download some of the manga's under the 'Mature' category, but they are always listed with zero chapters.

One of the example: [https://www.manhuagui.com/comic/7826/](url)
and this as well: [http://www.manhuagui.com/comic/26224/](url)

Is there any workaround for this?

**Comment by Slasar41** [comment] 2020-02-16 05:46
Duplicate of https://github.com/fmd-project-team/FMD/issues/579
Wait for someone able to fix it.

**Closed** 2020-02-16 07:34 UTC
Labels: Bug, Duplicate

**Comment by mirlov** [comment] 2020-02-17 13:25
Thank you for fixing this bug.
