### ISSUE TITLE
hitomi.la does not download

### ISSUE THREAD

**Issue by Dgraid12** [fmd-project-team/FMD#732] opened 2020-01-14 12:16 UTC
the list of sleeves appears but at the beginning of the download it always goes from 0 to 1 and never ends or continues after that point

![imagen](https://user-images.githubusercontent.com/53473707/72343780-0daaf480-36a6-11ea-951c-68fd80eb9d72.png)

**Comment by Tmp341** [comment] 2020-01-14 12:18
Duplicate of #599

**Closed by Tmp341** 2020-01-14 12:18 UTC
Labels: Duplicate, Site Changed

**Comment by Tmp341** [comment] 2020-01-14 12:20
Please search before opening an issue. And follow the other issue.
