### ISSUE TITLE
Option to change the default download path for the favorites list

### ISSUE THREAD

**Issue by AzeZero** [fmd-project-team/FMD#455] opened 2019-08-28 19:20 UTC
hi

i switched my pc, now i wanted to download some chapter on my new but i can't when i change the default download path to the new on then the path of my favorites list doesn't change. I don't want to change them manuel i have over 800 favorites.

**Comment by SDXC** [comment] 2019-08-30 15:41
This has been requested early on when I started this fork. I know I neglected this one quite a bit, but I will add this for the next release. As this issue is a duplicate of this one https://github.com/fmd-project-team/FMD/issues/10 , I'll close it. You can subscribe to the other issue so you get a notification when I implemented it, or just check the release notes when I publish the new version (it won't be too long anymore until then).

If you can't wait 1-2 weeks, there's also a workaround described in the issue I linked.

**Closed by SDXC** 2019-08-30 15:41 UTC
Labels: Decision Pending, Feature Request
