### ISSUE TITLE
[Option] Keep color coding visible in Favorites tab

### ISSUE THREAD

**Issue by TeepoLurking** [fmd-project-team/FMD#885] opened 2020-04-01 18:47 UTC
I've got nearly 400 entries in favorites and a lot of them are completed.
Automatic removal is too risky and thus needs to be done manually. 

It would be really nice if we saw manga release status directly in the favorites tab, even after FMD is done checking for new chapters.

At this moment the green color coding is removed as soon as checking is done, but it would be very useful to have visible all the time. It would be much easier to go through the "completed" entries.

Also if we could sort them by status, that would be even better.

**Comment by Slasar41** [comment] 2020-04-02 05:10
The color one has been requested: https://github.com/fmd-project-team/FMD/issues/127.

**Comment by Tmp341** [comment] 2020-04-02 07:55
Duplicate of #127

**Closed by Tmp341** 2020-04-02 07:55 UTC
Labels: Duplicate, Rejected
