### ISSUE TITLE
ReadmangaRu MintMangaRU not downloading last pages

### ISSUE THREAD

**Issue by LordARTOG** [fmd-project-team/FMD#750] opened 2020-01-27 05:44 UTC
I dicovered that FMD skip the last couple of pages when downloading via ReadMangaRU and MintMangaRU sites. Can you help with it?

**Comment by Tmp341** [comment] 2020-01-27 08:18
Duplicate of #733

**Comment by Tmp341** [comment] 2020-01-27 08:18
You can check issue #733

**Closed by Tmp341** 2020-01-27 08:18 UTC
Labels: Duplicate, Lua
