### ISSUE TITLE
Only white pages in PDF for some chapters

### ISSUE THREAD

**Issue by Vantageright** [fmd-project-team/FMD#430] opened 2019-08-16 09:12 UTC
I downloaded chapter 56 of [this manga](https://mangadex.org/title/19526/musuko-ga-kawaikute-shikataganai-mazoku-no-hahaoya) and have found that each of the multiple downloads have been unusable. Acrobat and firefox show entirely blank documents with the former stating the document has an error.

**Comment by SDXC** [comment] 2019-08-16 11:30
This is a problem that comes with the images.
It is a known problem, that GIMP 2.10.10 creates an invalid icc/color profile which other applications sometimes can't handle. In this case FMD as well. This has to be fixed by the scanlator/uploader by removing the ICC profile or updating to the latest GIMP version and re-save the images.

Here the bugreport:
https://gitlab.gnome.org/GNOME/gimp/issues/2111

This is not really a problem of FMD. If this problem only occurs with a small set of mangas, we won't add any additional workarounds for this.

**Comment by SDXC** [comment] 2019-08-16 11:56
I also did another test: the same files also can't be converted to JPEG. They remain as PNG. Chapter 49 for example works perfectly for PDF and JPEG conversion.

So the problem is the part where FMD tries to read the PNG which fails. This is an underlying problem of the base libraries of the programming language Pascal used for FMD. The library itself can't handle these files.

**Closed** 2019-08-21 12:26 UTC
Labels: No FMD Issue
