### ISSUE TITLE
How to avoid from mangabase update causing everything to reset?

### ISSUE THREAD

**Issue by Tensai-Otaku** [fmd-project-team/FMD#677] opened 2019-12-10 16:58 UTC
I don't know how to properly describe this, but basically whenever the update options pop up for all the update. After every restart, I am forced to re-add the manga site, and it's really annoying. Is there any solution to keep this from happening or a way to make sure the selected manga site don't get reset ever again?

**Comment by Tmp341** [comment] 2019-12-10 19:12
You mean modules? Can you post some screenshots what happens?

**Comment by Tensai-Otaku** [comment] 2019-12-10 19:33
It's hard to add pictures to describe my problem. Let me try it again with words instead.

Let's say I add Mangasee as a website to download manga from. After the module, updates appear occasionally and it tells me to restart. I can't search for manga on that website anymore after the restart. I need to add that website all over again from within option --> websites tab, and doing this multiple times gets annoying. I hope you understood it better this time around. Thank you for the speedy answer.

**Comment by Tmp341** [comment] 2019-12-11 05:21
What version you are/were using (fmd latest or riderkick vXXXX etc)?

**Comment by Tensai-Otaku** [comment] 2019-12-11 15:12
It was even happening in the old version of FMD before I moved to the latest. Even now with the latest update 0.9.167.2, it's still happening. I am running Windows 10 build 1909 in case that might be important. It's been occurring every since I started using FMD and the module started to request for an update. If the website I was currently using needed the update. I was forced to re-add it back from options --> websites section as previously noted.

**Comment by zartzaku** [comment] 2019-12-11 17:02
I also have the same problem. but now they didnt ask to update again but most of them is error in date. and when i check the lua many are gone.
![fmd](https://user-images.githubusercontent.com/14165907/70642851-8ddad600-1c72-11ea-801c-fa3b3e10f470.jpg)

**Comment by JokoeSukri** [comment] 2019-12-11 19:36
This was happening to me as well(often), The cause is the internet connection was cut-off while FMD.exe is still active, The luas always trying to connect and update automatically but there is no internet connection meanwhile the luas became old itself.
I have 2 alternatives, 
1, Always unchecked "Show Update Warning"
2. Close FMD when you have no internet connection.

**Comment by Tmp341** [comment] 2019-12-13 05:52
Oh that. When there is no connection, FMD thinks it as modules are gone, deletes existing modules.

**Comment by Tensai-Otaku** [comment] 2019-12-23 13:42
Sorry for the late reply. But the issue still persists after following JokoeSukri examples

**Comment by dazedcat19** [comment] 2019-12-27 23:25
unchecking show update warning only hide the dialog and auto confirm the dialog. you need to disable the auto check modules. it's tied with auto check fmd. so, you disable that thing.

**Comment by SDXC** [comment] 2019-12-28 11:51
It has been fixed by @dazedcat19 and will be part of the next version.

**Comment by SDXC** [comment] 2020-01-18 17:11
New version has been released.

**Closed by SDXC** 2020-01-18 17:11 UTC
Labels: Bug, Fixed, Wait For Release
