### ISSUE TITLE
Manga4life.com still having issue with certain chapters not showing up on fmd

### ISSUE THREAD

**Issue by jillybeans** [fmd-project-team/FMD#913] opened 2020-04-15 04:28 UTC
still having issue with certain chapters not showing up on fmd

https://manga4life.com/manga/Kochou-No-Yumeji

chapters 33-142 arnt showing up
https://manga4life.com/read-online/Kochou-No-Yumeji-chapter-141.html

and a new issue with chapters showing up on FMD that are not on the site

https://manga4life.com/read-online/Mairimashita-Iruma-kun-chapter-99.html

is the latest one but shows a chapter 100 that doesn't exist

Duplicate of #912
just noticed there is an opened issue for the non existing chapters showing up

_Originally posted by @jillybeans in https://github.com/fmd-project-team/FMD/issues/891#issuecomment-613808576_

**Comment by Tmp341** [comment] 2020-04-15 07:17
Duplicate of 891

**Closed by Tmp341** 2020-04-15 07:17 UTC

**Comment by Tmp341** [comment] 2020-04-15 07:20
It becomes hard for use to track multiple issues with the same problem on the same site. Please use older issues.
