### ISSUE TITLE
Create a rating system for each site and its quality

### ISSUE THREAD

**Issue by ahmadi3d** [fmd-project-team/FMD#840] opened 2020-02-29 18:16 UTC
This is a feature request
I think we can easily create a rating system for each site and its quality, the user simply rate a site between 1 and 10, and this score can be saved inside a server, a mac/ip address check can be used to stop users from abusing the rating system.

**Comment by Tmp341** [comment] 2020-02-29 18:20
Duplicate of #82

**Closed by Tmp341** 2020-02-29 18:20 UTC
