### ISSUE TITLE
Can't download certain webtoons from mangadex even with my account in FMD

### ISSUE THREAD

**Issue by syleniaa** [fmd-project-team/FMD#937] opened 2020-04-21 23:25 UTC
i am trying to download https://mangadex.org/title/35013/why-are-you-doing-this-duke but it gives e error.
 i already added my account and it was working ok, but after i closed and opened again FMD the manga that was downloading ok it gives an error now. i havent change anything, the account is still there , i already checked in the website and i can read those chapters with my account

**Comment by Tmp341** [comment] 2020-04-22 05:23
Duplicate of #935

**Closed by Tmp341** 2020-04-22 05:23 UTC
